### ISSUE TITLE
你好，请问以后missingalgo_qp.p中的代码会公开么

### ISSUE THREAD

**Issue by Mazeqi** [wangsiwei2010/CVPR22-IMVC-CBG#1]
你好，请问以后missingalgo_qp.p中的代码会公开么

**Comment by wangsiwei2010** [comment]
目前已在新一轮投稿中，详细的优化过程与这篇工作类似，初始化方式不同，missingalgo_qp.m优化代码可参考这份工作https://github.com/wangsiwei2010/SPMVC-CAG
